from typing import List, NamedTuple, Optional, TYPE_CHECKING
import numpy as np
import slicer
from slicer import vtkMRMLScalarVolumeNode
from slicer.parameterNodeWrapper import parameterPack
from OpenLIFULib.parameter_node_utils import (
    SlicerOpenLIFUSolutionWrapper,
    SlicerOpenLIFUSolutionAnalysis,
)
from OpenLIFULib.simulation import (
    make_volume_from_xarray_in_transducer_coords,
    make_xarray_in_transducer_coords_from_volume,
)
from OpenLIFULib.transducer import SlicerOpenLIFUTransducer

if TYPE_CHECKING:
    import openlifu
    import openlifu.plan
    import xarray

@parameterPack
class SlicerOpenLIFUSolution:
    """Information that is generated by running the SlicerOpenLIFU planning module"""

    solution : SlicerOpenLIFUSolutionWrapper
    """Underlying openlifu Solution in a thin wrapper"""

    pnp : vtkMRMLScalarVolumeNode
    """Peak negative pressure volume, aggregated over the results from each focus point"""

    intensity : vtkMRMLScalarVolumeNode
    """Average intensity volume, aggregated over the results from each focus point"""

    analysis : Optional[SlicerOpenLIFUSolutionAnalysis] = None
    """Solution analysis (PNP / ISPPA / ISPTA / MI / TIC / beamwidths / temperature).

    Owned by the solution so switching the active solution atomically brings its own
    analysis with it (no separate planner-parameter-node bookkeeping). Populated at
    compute time (see :meth:`OpenLIFUSonicationPlannerLogic.computeSolution`) and at
    session-load time (see :meth:`OpenLIFUDataLogic._restore_solutions_for_loaded_session`);
    ``None`` only for solutions that predate this field or whose analysis file is missing.
    """

    @staticmethod
    def initialize_from_openlifu_data(
        solution : "openlifu.plan.Solution",
        pnp_datarray : "xarray.DataArray",
        intensity_dataarray : "xarray.DataArray",
        transducer : SlicerOpenLIFUTransducer,
        analysis : Optional[SlicerOpenLIFUSolutionAnalysis] = None,
    ) -> "SlicerOpenLIFUSolution":
        """Create a SlicerOpenLIFUSolution from an openlifu Solution and aggregated data arrays to visualize,
        loading those data arrays into the scene as volume nodes.

        Args:
            solution: OpenLIFU Solution
            pnp_datarray: Peak negative pressure volumetric data array to visualize
            intensity_dataarray: Intensity volumetric data array to visualize
            transducer: SlicerOpenLIFUTransducer, needed to put simulation outputs in the right coordinate system
            analysis: Optional pre-computed analysis to attach; the analysis field can also be assigned later.
        """

        pnp_volume_node = make_volume_from_xarray_in_transducer_coords(pnp_datarray, transducer)
        intensity_volume_node = make_volume_from_xarray_in_transducer_coords(intensity_dataarray, transducer)

        pnp_volume_node.GetDisplayNode().SetAndObserveColorNodeID("vtkMRMLColorTableNodeFilePlasma.txt")
        intensity_volume_node.GetDisplayNode().SetAndObserveColorNodeID("vtkMRMLColorTableNodeFilePlasma.txt")

        # Set openlifu solution attribute
        pnp_volume_node.SetAttribute('isOpenLIFUSolution', 'True')
        intensity_volume_node.SetAttribute('isOpenLIFUSolution', 'True')

        return SlicerOpenLIFUSolution(
            SlicerOpenLIFUSolutionWrapper(solution),
            pnp_volume_node,
            intensity_volume_node,
            analysis,
        )

    @staticmethod
    def initialize_from_loaded_openlifu_solution(
        solution : "openlifu.plan.Solution",
        transducer : SlicerOpenLIFUTransducer,
        analysis : Optional[SlicerOpenLIFUSolutionAnalysis] = None,
    ) -> "SlicerOpenLIFUSolution":
        """Create a SlicerOpenLIFUSolution from an openlifu Solution loaded from disk.

        Re-derives the aggregated pnp and intensity data arrays from the Solution's per-focus
        ``simulation_result`` using the same aggregation that ``Protocol.calc_solution`` originally applied:
        max over focal points for peak negative pressure, mean over focal points for time-averaged intensity.
        """
        sim = solution.simulation_result
        pnp_datarray = sim['p_min'].max(dim="focal_point_index", keep_attrs=True)
        intensity_dataarray = sim['intensity'].mean(dim="focal_point_index", keep_attrs=True)
        return SlicerOpenLIFUSolution.initialize_from_openlifu_data(
            solution=solution,
            pnp_datarray=pnp_datarray,
            intensity_dataarray=intensity_dataarray,
            transducer=transducer,
            analysis=analysis,
        )

    def clear_nodes(self) -> None:
        """Clear associated mrml nodes from the scene. Do this when removing a transducer."""
        slicer.mrmlScene.RemoveNode(self.pnp)
        slicer.mrmlScene.RemoveNode(self.intensity)

    def is_approved(self) -> bool:
        """Whether the matching SolutionInfo on the loaded session is marked approved.

        Approval lives on ``SolutionInfo.approved`` at the session-provenance layer
        (SlicerOpenLIFU#611): the openlifu ``Solution`` object itself no longer carries
        an ``approved`` field. Returns ``False`` if there is no loaded session or if the
        session has no ``SolutionInfo`` record for this solution's id.
        """
        # Imported lazily to avoid a circular import at OpenLIFULib load time.
        from OpenLIFULib.util import get_app_state
        loaded_session = get_app_state().loaded_session
        if loaded_session is None:
            return False
        sid = self.solution.solution.id
        for info in loaded_session.session.session.solutions:
            if info.solution_id == sid:
                return info.approved
        return False

    def toggle_approval(self) -> None:
        """Flip the approval flag on the matching SolutionInfo on the loaded session.

        Approval lives on ``SolutionInfo.approved`` (SlicerOpenLIFU#611). This mutates the
        in-memory openlifu ``Session`` object and reassigns ``loaded_session`` so the
        ``@parameterNodeWrapper`` picks up the change. Persistence to disk is the caller's
        responsibility (typically ``OpenLIFUDataLogic.toggle_solution_approval``).

        Raises ``RuntimeError`` if there is no loaded session, or if the loaded session has
        no ``SolutionInfo`` record for this solution's id.
        """
        from OpenLIFULib.util import get_app_state
        state = get_app_state()
        loaded_session = state.loaded_session
        if loaded_session is None:
            raise RuntimeError("Cannot toggle solution approval: no session is loaded.")
        sid = self.solution.solution.id
        session_openlifu = loaded_session.session.session
        for info in session_openlifu.solutions:
            if info.solution_id == sid:
                info.approved = not info.approved
                break
        else:
            raise RuntimeError(
                f"Cannot toggle solution approval: solution {sid!r} has no SolutionInfo record "
                "on the loaded session."
            )
        # Reassign the pack so ``@parameterNodeWrapper`` serializes the mutation.
        state.loaded_session = loaded_session
